### ISSUE TITLE
Overview of newly added accepting businesses

### ISSUE THREAD

**Issue by RoAnBu** [digitalfabrik/ehrenamtskarte#13]
As an owner of a EAK, I want to get an overview of recently added accepting businesses, so that I can quickly see if there is a new intersting accepting business for me.

Acceptance Criteria:
- [ ] Recently added accepting businesses can be viewed in descending order beginning with the most recent Akzeptanzstelle
- [ ] I can see if the accepting business is new for me (or if I have already seen it)
- [ ] I can see when the accepting business was added
- [ ] I can filter by a given location with a given or fixed radius

**Comment by maxammann** [comment]
This issue was created in the initial design/implementation phase of the eherenamtskarte. 
Therefore, I'll close this because it is probably outdated.
If this feature request is important then it will come up again in the future development of this app.
