### ISSUE TITLE
Map detail page still shown when using "show on map" button

### ISSUE THREAD

**Issue by elKei24** [digitalfabrik/ehrenamtskarte#173]
**To Reproduce**
- open details page of an accepting store on the map
- go to the search
- search an accepting business
- show its details
- click "show on map"
- the details page of the store previously selected on the map is still shown

**Expected behavior**
The navigation stack of the map tab is cleared when using the "show on map" button, so that the map is visible with the highlighted store from the search.

**Screenshots**
https://user-images.githubusercontent.com/13063245/104597736-fc5c4580-5675-11eb-86a9-5adbe1d1f585.mp4

**Comment by klinzo** [comment]
I think this is not an issue anymore, is it? When selecting an accepting store on the map and opening its detail page, the tab bar is not shown anymore. Therefore it is not possible to go to search while a details page is shown.
