### ISSUE TITLE
Ask users for Reviews on iOS

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/ehrenamtskarte#383]
As Digitalfabrik I want to ask users about a review: https://pub.dev/packages/app_review

Acceptance Criteria:
 - [ ] Ask users once for a review after using the app for 1 week

**Comment by Schedulaar** [comment]
Do we really want this and why do we only want this for iOS?

**Comment by maxammann** [comment]
Needs discussion on whether we want this or not. Maybe clarify with stakeholders.

**Comment by maxammann** [comment]
Lets just close this :D Its below low priority :D
