### ISSUE TITLE
Change icon of Freizeit/Reisen category

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/ehrenamtskarte#417]
**Describe the bug**
The current icon looks like a trash bin. Try to find a better one.

**Comment by klinzo** [comment]
Where are these icons from? Did you create them yourself?

**Comment by maxammann** [comment]
Hmmmm good question.. @PaulaWi do you know more?

**Comment by maxammann** [comment]
https://labs.mapbox.com/maki-icons/
