### ISSUE TITLE
Reenable rotation to and from landscape mode on Android

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/ehrenamtskarte#419]
**Describe the bug**
With https://github.com/ehrenamtskarte/ehrenamtskarte/issues/415 we set the orientation to portrait. While this is acceptable for phones, on tablets the preferred orientation is actually landscape.

**To Reproduce**
See https://github.com/ehrenamtskarte/ehrenamtskarte/issues/415

**Desktop (please complete the following information):**
 - OS: Android Emulator and Real Device

**Comment by maxammann** [comment]
Reported upstream: https://github.com/m0nac0/flutter-maplibre-gl/issues/54

**Comment by maxammann** [comment]
Workaround available: https://github.com/flutter-mapbox-gl/maps/issues/195

**Comment by Schedulaar** [comment]
Actually a high prio for me: It is just not the usual way to use tablets in portrait mode.

**Comment by maxammann** [comment]
My first attempt failed. Let's see what users write here: https://github.com/flutter-mapbox-gl/maps/issues/195

**Comment by maxammann** [comment]
I managed to fix this with the following helper: https://github.com/digitalfabrik/ehrenamtskarte/blob/b8363ca82f9db2c6e06ab2ea4d616a7293e21dd8/frontend/lib/map/map/screen_parent_resizer.dart
