### ISSUE TITLE
(Needs reproduction) Determine location loads forever if disabled in settings

### ISSUE THREAD

**Issue by klinzo** [digitalfabrik/ehrenamtskarte#432]
**Describe the bug**
If location is disabled in settings

**To Reproduce**
1. Open the app
2. Disable location in settings
3. Click on determine location button
4. Determine location loads forever

**Expected behavior**
The determine location does not load and shows a toast or similar instead to notify the user that location needs to enabled in settings.

**Smartphone:**
 - Device: Xiaomi Mi Mix 2
 - OS: Android 11, Lineage OS 18.1 with microG
 - Version 2.0.2

**Additional context**
It may be related to not having Google Play Services installed.

**Comment by maxammann** [comment]
@Schedulaar could you try to reproduce this on a "normal" android?

**Comment by Schedulaar** [comment]
Cannot reproduce this (version 2.1.1):

https://user-images.githubusercontent.com/7025199/150178496-41643569-71c3-465b-b29b-5ca148c00e76.mp4

**Comment by maxammann** [comment]
Thank you  :)
