### ISSUE TITLE
(Requires reproduction) Initial map bounding box is broken

### ISSUE THREAD

**Issue by klinzo** [digitalfabrik/ehrenamtskarte#434]
**Is your feature request related to a problem? Please describe.**
Currently the default map bounding box is the whole of bavaria. If I want to see stores in my surrounding (which is probably the main use case), I have to zoom in or click on the determine location button.

**Describe the solution you'd like**
If I granted location permission and the app does have my current location, I would perhaps find it more intuitive to center the map around my position with a reasonable zoom.

**Comment by Schedulaar** [comment]
The default actually is (or was until recently; I dont know if that has changed) the current location of the user. We have a timeout though with ~500ms. If the user location could not be determined within that time span when the app starts up, we show the whole of bavaria.

**Comment by klinzo** [comment]
For me that does not work at least, but maybe it is because of my phone.

**Comment by Schedulaar** [comment]
I think without using Google Play Services, determining the user's location takes a huge amount longer...

**Comment by klinzo** [comment]
Yep, maybe is that the problem. However, I tested this also with mocking my location (which should return the location directly) and it also did not work. Maybe you could just test this on your phone once?

**Comment by klinzo** [comment]
In the version on GPlay it works for me as well, so I think this is a valid bug in the current app state on main.

**Comment by maxammann** [comment]
I just tested this:
* on my phone without google services (and without gapps) - main branch works
* ipad - latest release works

**Comment by maxammann** [comment]
@Schedulaar can you test on your android?

**Comment by klinzo** [comment]
Then probably just another gplay issue
