### ISSUE TITLE
Add caching for geocoding requests

### ISSUE THREAD

**Issue by klinzo** [digitalfabrik/ehrenamtskarte#445]
**Is your feature request related to a problem? Please describe.**
We are doing the import of the eak data once a week. With #439 we introduce geocoding which needs lots of requests to our geocoding backend, which needs lots of time and resources.

**Describe the solution you'd like**
Since the data and therefore the responses in our geocoding backend is mostly static, we could introduce client side caching to reduce the necessary time and resources needed to sanitize the data.

**Options**
* Manual caching with a cache dir (was implemented partially already but removed here again https://github.com/digitalfabrik/ehrenamtskarte/pull/439/commits/0507bbef71c61f49c322c14447cc016c69750bb6)
* Implement the following interface: https://api.ktor.io/ktor-client/ktor-client-core/io.ktor.client.plugins.cache.storage/-http-cache-storage/index.html
* Move the caching to the database

**Things to keep in mind**
* Maximum cache size (max. files and max. size in bytes)
* Invalidation
* Handling errors like: Out of Storage, No permission etc.
* Safe file names (no special characters)

See discussion:
https://github.com/digitalfabrik/ehrenamtskarte/pull/439#discussion_r782013444

**Comment by maxammann** [comment]
Closing because the geocoding finishes within 1-3 minutes on the server.
